### ISSUE TITLE
Some questions about training from scratch

### ISSUE THREAD

**Issue by enjoybo** [shrubb/latent-pose-reenactment#32]
Hi Egor Burkov, thanks for your great project. Now I'm trying to train the meta learning model from scratch, however, the training results are not good as your model. Our dataset is much smaller (625 people) than VoxCeleb2. Is this the major reason that the training results look not great as yours? What is the most important factor affecting the performance of the model?

**Comment by shrubb** [comment]
Hi, thanks. 625 people is **definitely** not enough! At least for our method. At least it won't allow learning the pose-identity disentanglement. Also, when fine-tuning to a new person in test time, you'll need more iterations (because the system has seem a smaller number of diverse faces), which means you'll lose more mimics' expressiveness.

**Comment by enjoybo** [comment]
Thanks for your quick reply. We are expanding the dataset now. I have another question, did you join train the model end2end?

**Comment by shrubb** [comment]
Yes. The paper may give you more details on training.11:10, 10 сентября 2021 г., enjoybo ***@***.***>:
Thanks for your quick reply. We are expanding the dataset now. I have another question, did you join train the model end2end?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail
