### ISSUE TITLE
Speed up preprocessing step?

### ISSUE THREAD

**Issue by monic7** [shrubb/latent-pose-reenactment#40]
Hi, I have cloned this repo and used the utils/preprocess_dataset.sh as it is to preprocess VoxCeleb2 dataset. It has been more than 2 months but only about 1/6 of the dataset has been processed. Is this the normal speed of preprocessing or have I done anything wrong? If it helps, I am running on 2 RTX3080 GPUs with all default settings. 
Where do I need to change to speed up the preprocessing stage? 
Where can I increase the batch size for preprocessing and for the Graphonomy model? 
Thank you

**Comment by shrubb** [comment]
Hi, indeed, the preprocessing script here is intended for small sets of images. For preprocessing VoxCeleb2, I used a different version of it. I don't have it anymore, but it had multi-process execution, large batches, and parallel loading from disk (using `torch.utils.data.DataLoader`).

Graphonomy should be OK if used properly. The bottleneck must be in `crop_as_in_dataset.py` because (but not only) it re-loads the face detector before every run.
